config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :tasks

  devise_for :users
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attributes/postgres_friendly_time_zone.rb
class PostgresFriendlyTimeZone < ActiveRecord::Type::String
  def serialize(value)
    ActiveSupport::TimeZone::MAPPING[value]
  end

  def deserialize(value)
    ActiveSupport::TimeZone::MAPPING.invert[value]
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable


  attribute :time_zone, PostgresFriendlyTimeZone.new

  phony_normalize :phone_number, default_country_code: 'US'

  validates :phone_number, phony_plausible: {
    ignore_record_country_code: true,
    ignore_record_country_number: true
  }

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  UPDATEABLE_DEVISE_KEYS = [
    :phone_number,
    :time_zone
  ].freeze

  protect_from_forgery with: :exception

  around_action :set_time_zone, if: :current_user
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: UPDATEABLE_DEVISE_KEYS )
    devise_parameter_sanitizer.permit(:account_update, keys: UPDATEABLE_DEVISE_KEYS )
  end

  def set_time_zone(&block)
    Time.use_zone(current_user.time_zone, &block)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to tasks_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = current_user.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user

    if @task.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :time, days_of_week: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def day_to_short_day(day)
    case day
    when "Monday"
      "M"
    when "Tuesday"
      "T"
    when "Wednesday"
      "W"
    when "Thursday"
      "TH"
    when "Friday"
      "F"
    when "Saturday"
      "S"
    when "Sunday"
      "SU"
    end
  end
end

app/views/home/index.html.erb
<h1>Procrastidont</h1>
<p>The app to help you when you have procrastinative tendencies.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Procrastidont</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header>
      <%= link_to root_path do %>
        <h1 class="logo">Procrastidont</h1>
      <% end %>

      <nav class="navbar">
        <% if user_signed_in?%>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          <%= link_to edit_user_registration_path do %>
            <img class="current-avatar" src="<%= gravatar_url(current_user) %>"/>
          <% end %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %>
          <%= link_to "Login", user_session_path %>
        <% end %>
      </nav>
    </header>

    <% if notice %>
      <div class="flash-container notice">
        <p class="flash"><%= notice %></p>
      </div>
    <% end %>

    <% if alert %>
      <div class="flash-container alert">
        <p class="flash"><%= alert %></p>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="task-form">
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :time %>

  <div class="time-select">
    <%= f.time_select :time, default: Time.current %>
  </div>

  <%= f.label :days_of_week %>
  <div class="days-of-week">
    <% Date::DAYNAMES.each do |day| %>
      <%= f.check_box :days_of_week,
        { multiple: true, checked: task.days_of_week.include?(day.downcase) },
        day.downcase,
        nil
      %>
    <%= f.label "days_of_week_#{day.downcase}", day %>
  <% end %>
</div>
</div>

app/views/tasks/edit.html.erb
<div class="form-header">
  <h1> Edit Task </h1>
</div>

<%= form_for @task, html: { class: "task-form" }  do |f| %>
  <%= render "form", f: f, task: @task %>

  <div class="actions">
    <%= f.submit "Update task" %>
  </div>
<% end %>

<%= link_to "Delete Task", task_path(@task), method: :delete %>

app/views/tasks/index.html.erb
<div class="container">
  <div class="task-header">
    <h1 class="title">My Tasks</h1>

    <%= link_to "Create task", task_path(:new), class: "button" %>
  </div>

  <% if @tasks.empty? %>
    <h2 class="subtitle"> You have no tasks! </h2>
  <% else %>
    <% @tasks.each do |task| %>
      <%= link_to edit_task_path(task), class: "task" do %>
        <div class="details">
          <h2 class="title">
            <%= task.title %>
          </h2>
          <p class="description"><%= task.description %></p>
        </div>

        <div class="time-and-days">
          <small class="time"><%= task.time.strftime("%H:%M%p") %></small>
          <div>
            <% Date::DAYNAMES.each do |day| %>
              <span class="day <%= "active" if task.days_of_week.include?(day.downcase) %>">
                <%= day_to_short_day(day) %>
              </span>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class=form-header">
  <h1>New Task</h1>
</div>

<%= form_for @task, html: { class: "task-form" } do |f| %>
  <%= render "form", f: f, task: @task %>

  <div class="actions">
    <%= f.submit "Create task" %>
  </div>

<% end %>